name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/back_calc:latest

  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest ruff
        pip install -r requirements.txt
        pip install httpx
    
    - name: Ejecutar pruebas con Pytest
      run: coverage run -m pytest -v -s
    
    - name: Ejecutar Ruff
      run: ruff check

  build-and-push-github-package:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Copiar código
          uses: actions/checkout@v4
        -
          name: Login en GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.PACKAGE_TOKEN }}
        -
          name: Build image y pushear a Github Packages
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/Yagoo23/calculadora-backend

